// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

public interface ClinicalDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.integration.ClinicalDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return The trace.
   */
  com.mdt.integration.grpc.Trace getTrace();
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   */
  com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder();

  /**
   * <code>string patient_visit_uid = 2;</code>
   * @return The patientVisitUid.
   */
  java.lang.String getPatientVisitUid();
  /**
   * <code>string patient_visit_uid = 2;</code>
   * @return The bytes for patientVisitUid.
   */
  com.google.protobuf.ByteString
      getPatientVisitUidBytes();

  /**
   * <pre>
   * HIS/EMR/LIS
   * </pre>
   *
   * <code>repeated string source = 3;</code>
   * @return A list containing the source.
   */
  java.util.List<java.lang.String>
      getSourceList();
  /**
   * <pre>
   * HIS/EMR/LIS
   * </pre>
   *
   * <code>repeated string source = 3;</code>
   * @return The count of source.
   */
  int getSourceCount();
  /**
   * <pre>
   * HIS/EMR/LIS
   * </pre>
   *
   * <code>repeated string source = 3;</code>
   * @param index The index of the element to return.
   * @return The source at the given index.
   */
  java.lang.String getSource(int index);
  /**
   * <pre>
   * HIS/EMR/LIS
   * </pre>
   *
   * <code>repeated string source = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the source at the given index.
   */
  com.google.protobuf.ByteString
      getSourceBytes(int index);
}
