// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

public interface ClinicalDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.integration.ClinicalDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * 脱敏后的临床数据（JSON）
   * </pre>
   *
   * <code>string emr_json = 2;</code>
   * @return The emrJson.
   */
  java.lang.String getEmrJson();
  /**
   * <pre>
   * 脱敏后的临床数据（JSON）
   * </pre>
   *
   * <code>string emr_json = 2;</code>
   * @return The bytes for emrJson.
   */
  com.google.protobuf.ByteString
      getEmrJsonBytes();
}
