// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

/**
 * <pre>
 * 从 HIS/EMR/LIS 经视图/中间表拉取临床数据
 * </pre>
 *
 * Protobuf type {@code mdt.integration.ClinicalDataRequest}
 */
public final class ClinicalDataRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mdt.integration.ClinicalDataRequest)
    ClinicalDataRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClinicalDataRequest.newBuilder() to construct.
  private ClinicalDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClinicalDataRequest() {
    patientVisitUid_ = "";
    source_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClinicalDataRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_ClinicalDataRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_ClinicalDataRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdt.integration.grpc.ClinicalDataRequest.class, com.mdt.integration.grpc.ClinicalDataRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TRACE_FIELD_NUMBER = 1;
  private com.mdt.integration.grpc.Trace trace_;
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  @java.lang.Override
  public boolean hasTrace() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return The trace.
   */
  @java.lang.Override
  public com.mdt.integration.grpc.Trace getTrace() {
    return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
  }
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   */
  @java.lang.Override
  public com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder() {
    return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
  }

  public static final int PATIENT_VISIT_UID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object patientVisitUid_ = "";
  /**
   * <code>string patient_visit_uid = 2;</code>
   * @return The patientVisitUid.
   */
  @java.lang.Override
  public java.lang.String getPatientVisitUid() {
    java.lang.Object ref = patientVisitUid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patientVisitUid_ = s;
      return s;
    }
  }
  /**
   * <code>string patient_visit_uid = 2;</code>
   * @return The bytes for patientVisitUid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPatientVisitUidBytes() {
    java.lang.Object ref = patientVisitUid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patientVisitUid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList source_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * HIS/EMR/LIS
   * </pre>
   *
   * <code>repeated string source = 3;</code>
   * @return A list containing the source.
   */
  public com.google.protobuf.ProtocolStringList
      getSourceList() {
    return source_;
  }
  /**
   * <pre>
   * HIS/EMR/LIS
   * </pre>
   *
   * <code>repeated string source = 3;</code>
   * @return The count of source.
   */
  public int getSourceCount() {
    return source_.size();
  }
  /**
   * <pre>
   * HIS/EMR/LIS
   * </pre>
   *
   * <code>repeated string source = 3;</code>
   * @param index The index of the element to return.
   * @return The source at the given index.
   */
  public java.lang.String getSource(int index) {
    return source_.get(index);
  }
  /**
   * <pre>
   * HIS/EMR/LIS
   * </pre>
   *
   * <code>repeated string source = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the source at the given index.
   */
  public com.google.protobuf.ByteString
      getSourceBytes(int index) {
    return source_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientVisitUid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, patientVisitUid_);
    }
    for (int i = 0; i < source_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, source_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientVisitUid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, patientVisitUid_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < source_.size(); i++) {
        dataSize += computeStringSizeNoTag(source_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getSourceList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdt.integration.grpc.ClinicalDataRequest)) {
      return super.equals(obj);
    }
    com.mdt.integration.grpc.ClinicalDataRequest other = (com.mdt.integration.grpc.ClinicalDataRequest) obj;

    if (hasTrace() != other.hasTrace()) return false;
    if (hasTrace()) {
      if (!getTrace()
          .equals(other.getTrace())) return false;
    }
    if (!getPatientVisitUid()
        .equals(other.getPatientVisitUid())) return false;
    if (!getSourceList()
        .equals(other.getSourceList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTrace()) {
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace().hashCode();
    }
    hash = (37 * hash) + PATIENT_VISIT_UID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientVisitUid().hashCode();
    if (getSourceCount() > 0) {
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSourceList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mdt.integration.grpc.ClinicalDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mdt.integration.grpc.ClinicalDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.integration.grpc.ClinicalDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdt.integration.grpc.ClinicalDataRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 从 HIS/EMR/LIS 经视图/中间表拉取临床数据
   * </pre>
   *
   * Protobuf type {@code mdt.integration.ClinicalDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mdt.integration.ClinicalDataRequest)
      com.mdt.integration.grpc.ClinicalDataRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_ClinicalDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_ClinicalDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdt.integration.grpc.ClinicalDataRequest.class, com.mdt.integration.grpc.ClinicalDataRequest.Builder.class);
    }

    // Construct using com.mdt.integration.grpc.ClinicalDataRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      patientVisitUid_ = "";
      source_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_ClinicalDataRequest_descriptor;
    }

    @java.lang.Override
    public com.mdt.integration.grpc.ClinicalDataRequest getDefaultInstanceForType() {
      return com.mdt.integration.grpc.ClinicalDataRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdt.integration.grpc.ClinicalDataRequest build() {
      com.mdt.integration.grpc.ClinicalDataRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdt.integration.grpc.ClinicalDataRequest buildPartial() {
      com.mdt.integration.grpc.ClinicalDataRequest result = new com.mdt.integration.grpc.ClinicalDataRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mdt.integration.grpc.ClinicalDataRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trace_ = traceBuilder_ == null
            ? trace_
            : traceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.patientVisitUid_ = patientVisitUid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        source_.makeImmutable();
        result.source_ = source_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdt.integration.grpc.ClinicalDataRequest) {
        return mergeFrom((com.mdt.integration.grpc.ClinicalDataRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdt.integration.grpc.ClinicalDataRequest other) {
      if (other == com.mdt.integration.grpc.ClinicalDataRequest.getDefaultInstance()) return this;
      if (other.hasTrace()) {
        mergeTrace(other.getTrace());
      }
      if (!other.getPatientVisitUid().isEmpty()) {
        patientVisitUid_ = other.patientVisitUid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.source_.isEmpty()) {
        if (source_.isEmpty()) {
          source_ = other.source_;
          bitField0_ |= 0x00000004;
        } else {
          ensureSourceIsMutable();
          source_.addAll(other.source_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTraceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              patientVisitUid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureSourceIsMutable();
              source_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.mdt.integration.grpc.Trace trace_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder> traceBuilder_;
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     * @return Whether the trace field is set.
     */
    public boolean hasTrace() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     * @return The trace.
     */
    public com.mdt.integration.grpc.Trace getTrace() {
      if (traceBuilder_ == null) {
        return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
      } else {
        return traceBuilder_.getMessage();
      }
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder setTrace(com.mdt.integration.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trace_ = value;
      } else {
        traceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder setTrace(
        com.mdt.integration.grpc.Trace.Builder builderForValue) {
      if (traceBuilder_ == null) {
        trace_ = builderForValue.build();
      } else {
        traceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder mergeTrace(com.mdt.integration.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          trace_ != null &&
          trace_ != com.mdt.integration.grpc.Trace.getDefaultInstance()) {
          getTraceBuilder().mergeFrom(value);
        } else {
          trace_ = value;
        }
      } else {
        traceBuilder_.mergeFrom(value);
      }
      if (trace_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder clearTrace() {
      bitField0_ = (bitField0_ & ~0x00000001);
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public com.mdt.integration.grpc.Trace.Builder getTraceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTraceFieldBuilder().getBuilder();
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder() {
      if (traceBuilder_ != null) {
        return traceBuilder_.getMessageOrBuilder();
      } else {
        return trace_ == null ?
            com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
      }
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder> 
        getTraceFieldBuilder() {
      if (traceBuilder_ == null) {
        traceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder>(
                getTrace(),
                getParentForChildren(),
                isClean());
        trace_ = null;
      }
      return traceBuilder_;
    }

    private java.lang.Object patientVisitUid_ = "";
    /**
     * <code>string patient_visit_uid = 2;</code>
     * @return The patientVisitUid.
     */
    public java.lang.String getPatientVisitUid() {
      java.lang.Object ref = patientVisitUid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientVisitUid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patient_visit_uid = 2;</code>
     * @return The bytes for patientVisitUid.
     */
    public com.google.protobuf.ByteString
        getPatientVisitUidBytes() {
      java.lang.Object ref = patientVisitUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientVisitUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patient_visit_uid = 2;</code>
     * @param value The patientVisitUid to set.
     * @return This builder for chaining.
     */
    public Builder setPatientVisitUid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      patientVisitUid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string patient_visit_uid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPatientVisitUid() {
      patientVisitUid_ = getDefaultInstance().getPatientVisitUid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string patient_visit_uid = 2;</code>
     * @param value The bytes for patientVisitUid to set.
     * @return This builder for chaining.
     */
    public Builder setPatientVisitUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      patientVisitUid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList source_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureSourceIsMutable() {
      if (!source_.isModifiable()) {
        source_ = new com.google.protobuf.LazyStringArrayList(source_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @return A list containing the source.
     */
    public com.google.protobuf.ProtocolStringList
        getSourceList() {
      source_.makeImmutable();
      return source_;
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @return The count of source.
     */
    public int getSourceCount() {
      return source_.size();
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @param index The index of the element to return.
     * @return The source at the given index.
     */
    public java.lang.String getSource(int index) {
      return source_.get(index);
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the source at the given index.
     */
    public com.google.protobuf.ByteString
        getSourceBytes(int index) {
      return source_.getByteString(index);
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @param index The index to set the value at.
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSourceIsMutable();
      source_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @param value The source to add.
     * @return This builder for chaining.
     */
    public Builder addSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureSourceIsMutable();
      source_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @param values The source to add.
     * @return This builder for chaining.
     */
    public Builder addAllSource(
        java.lang.Iterable<java.lang.String> values) {
      ensureSourceIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, source_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * HIS/EMR/LIS
     * </pre>
     *
     * <code>repeated string source = 3;</code>
     * @param value The bytes of the source to add.
     * @return This builder for chaining.
     */
    public Builder addSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureSourceIsMutable();
      source_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mdt.integration.ClinicalDataRequest)
  }

  // @@protoc_insertion_point(class_scope:mdt.integration.ClinicalDataRequest)
  private static final com.mdt.integration.grpc.ClinicalDataRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdt.integration.grpc.ClinicalDataRequest();
  }

  public static com.mdt.integration.grpc.ClinicalDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClinicalDataRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClinicalDataRequest>() {
    @java.lang.Override
    public ClinicalDataRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClinicalDataRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClinicalDataRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdt.integration.grpc.ClinicalDataRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

