// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

/**
 * <pre>
 * SCP 推送落库：携带完整 DICOM 元数据（适配器已解析 PatientVisitUID 前的原始字段）
 * </pre>
 *
 * Protobuf type {@code mdt.integration.IngestStudyRequest}
 */
public final class IngestStudyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mdt.integration.IngestStudyRequest)
    IngestStudyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IngestStudyRequest.newBuilder() to construct.
  private IngestStudyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IngestStudyRequest() {
    studyInstanceUid_ = "";
    patientId_ = "";
    accessionNumber_ = "";
    tenantId_ = "";
    modality_ = "";
    studyDate_ = "";
    objectKey_ = "";
    reportContent_ = "";
    pathologyConclusion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IngestStudyRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_IngestStudyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_IngestStudyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdt.integration.grpc.IngestStudyRequest.class, com.mdt.integration.grpc.IngestStudyRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TRACE_FIELD_NUMBER = 1;
  private com.mdt.integration.grpc.Trace trace_;
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  @java.lang.Override
  public boolean hasTrace() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return The trace.
   */
  @java.lang.Override
  public com.mdt.integration.grpc.Trace getTrace() {
    return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
  }
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   */
  @java.lang.Override
  public com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder() {
    return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
  }

  public static final int STUDY_INSTANCE_UID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object studyInstanceUid_ = "";
  /**
   * <code>string study_instance_uid = 2;</code>
   * @return The studyInstanceUid.
   */
  @java.lang.Override
  public java.lang.String getStudyInstanceUid() {
    java.lang.Object ref = studyInstanceUid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studyInstanceUid_ = s;
      return s;
    }
  }
  /**
   * <code>string study_instance_uid = 2;</code>
   * @return The bytes for studyInstanceUid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStudyInstanceUidBytes() {
    java.lang.Object ref = studyInstanceUid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studyInstanceUid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATIENT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object patientId_ = "";
  /**
   * <code>string patient_id = 3;</code>
   * @return The patientId.
   */
  @java.lang.Override
  public java.lang.String getPatientId() {
    java.lang.Object ref = patientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patientId_ = s;
      return s;
    }
  }
  /**
   * <code>string patient_id = 3;</code>
   * @return The bytes for patientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPatientIdBytes() {
    java.lang.Object ref = patientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCESSION_NUMBER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accessionNumber_ = "";
  /**
   * <code>string accession_number = 4;</code>
   * @return The accessionNumber.
   */
  @java.lang.Override
  public java.lang.String getAccessionNumber() {
    java.lang.Object ref = accessionNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessionNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string accession_number = 4;</code>
   * @return The bytes for accessionNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccessionNumberBytes() {
    java.lang.Object ref = accessionNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessionNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 5;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 5;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODALITY_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object modality_ = "";
  /**
   * <code>string modality = 6;</code>
   * @return The modality.
   */
  @java.lang.Override
  public java.lang.String getModality() {
    java.lang.Object ref = modality_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modality_ = s;
      return s;
    }
  }
  /**
   * <code>string modality = 6;</code>
   * @return The bytes for modality.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModalityBytes() {
    java.lang.Object ref = modality_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modality_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDY_DATE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object studyDate_ = "";
  /**
   * <pre>
   * ISO yyyy-MM-dd
   * </pre>
   *
   * <code>string study_date = 7;</code>
   * @return The studyDate.
   */
  @java.lang.Override
  public java.lang.String getStudyDate() {
    java.lang.Object ref = studyDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studyDate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ISO yyyy-MM-dd
   * </pre>
   *
   * <code>string study_date = 7;</code>
   * @return The bytes for studyDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStudyDateBytes() {
    java.lang.Object ref = studyDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studyDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECT_KEY_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object objectKey_ = "";
  /**
   * <code>string object_key = 8;</code>
   * @return The objectKey.
   */
  @java.lang.Override
  public java.lang.String getObjectKey() {
    java.lang.Object ref = objectKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectKey_ = s;
      return s;
    }
  }
  /**
   * <code>string object_key = 8;</code>
   * @return The bytes for objectKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectKeyBytes() {
    java.lang.Object ref = objectKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTANCE_COUNT_FIELD_NUMBER = 9;
  private int instanceCount_ = 0;
  /**
   * <code>int32 instance_count = 9;</code>
   * @return The instanceCount.
   */
  @java.lang.Override
  public int getInstanceCount() {
    return instanceCount_;
  }

  public static final int REPORT_CONTENT_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reportContent_ = "";
  /**
   * <code>string report_content = 10;</code>
   * @return The reportContent.
   */
  @java.lang.Override
  public java.lang.String getReportContent() {
    java.lang.Object ref = reportContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportContent_ = s;
      return s;
    }
  }
  /**
   * <code>string report_content = 10;</code>
   * @return The bytes for reportContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReportContentBytes() {
    java.lang.Object ref = reportContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATHOLOGY_CONCLUSION_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pathologyConclusion_ = "";
  /**
   * <code>string pathology_conclusion = 11;</code>
   * @return The pathologyConclusion.
   */
  @java.lang.Override
  public java.lang.String getPathologyConclusion() {
    java.lang.Object ref = pathologyConclusion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pathologyConclusion_ = s;
      return s;
    }
  }
  /**
   * <code>string pathology_conclusion = 11;</code>
   * @return The bytes for pathologyConclusion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathologyConclusionBytes() {
    java.lang.Object ref = pathologyConclusion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pathologyConclusion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(studyInstanceUid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, studyInstanceUid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, patientId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessionNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accessionNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modality_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, modality_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(studyDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, studyDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, objectKey_);
    }
    if (instanceCount_ != 0) {
      output.writeInt32(9, instanceCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reportContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, reportContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pathologyConclusion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, pathologyConclusion_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(studyInstanceUid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, studyInstanceUid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, patientId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessionNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accessionNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(modality_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, modality_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(studyDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, studyDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(objectKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, objectKey_);
    }
    if (instanceCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, instanceCount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reportContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, reportContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pathologyConclusion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, pathologyConclusion_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdt.integration.grpc.IngestStudyRequest)) {
      return super.equals(obj);
    }
    com.mdt.integration.grpc.IngestStudyRequest other = (com.mdt.integration.grpc.IngestStudyRequest) obj;

    if (hasTrace() != other.hasTrace()) return false;
    if (hasTrace()) {
      if (!getTrace()
          .equals(other.getTrace())) return false;
    }
    if (!getStudyInstanceUid()
        .equals(other.getStudyInstanceUid())) return false;
    if (!getPatientId()
        .equals(other.getPatientId())) return false;
    if (!getAccessionNumber()
        .equals(other.getAccessionNumber())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getModality()
        .equals(other.getModality())) return false;
    if (!getStudyDate()
        .equals(other.getStudyDate())) return false;
    if (!getObjectKey()
        .equals(other.getObjectKey())) return false;
    if (getInstanceCount()
        != other.getInstanceCount()) return false;
    if (!getReportContent()
        .equals(other.getReportContent())) return false;
    if (!getPathologyConclusion()
        .equals(other.getPathologyConclusion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTrace()) {
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace().hashCode();
    }
    hash = (37 * hash) + STUDY_INSTANCE_UID_FIELD_NUMBER;
    hash = (53 * hash) + getStudyInstanceUid().hashCode();
    hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientId().hashCode();
    hash = (37 * hash) + ACCESSION_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getAccessionNumber().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + MODALITY_FIELD_NUMBER;
    hash = (53 * hash) + getModality().hashCode();
    hash = (37 * hash) + STUDY_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getStudyDate().hashCode();
    hash = (37 * hash) + OBJECT_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getObjectKey().hashCode();
    hash = (37 * hash) + INSTANCE_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getInstanceCount();
    hash = (37 * hash) + REPORT_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getReportContent().hashCode();
    hash = (37 * hash) + PATHOLOGY_CONCLUSION_FIELD_NUMBER;
    hash = (53 * hash) + getPathologyConclusion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mdt.integration.grpc.IngestStudyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mdt.integration.grpc.IngestStudyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.integration.grpc.IngestStudyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdt.integration.grpc.IngestStudyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * SCP 推送落库：携带完整 DICOM 元数据（适配器已解析 PatientVisitUID 前的原始字段）
   * </pre>
   *
   * Protobuf type {@code mdt.integration.IngestStudyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mdt.integration.IngestStudyRequest)
      com.mdt.integration.grpc.IngestStudyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_IngestStudyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_IngestStudyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdt.integration.grpc.IngestStudyRequest.class, com.mdt.integration.grpc.IngestStudyRequest.Builder.class);
    }

    // Construct using com.mdt.integration.grpc.IngestStudyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      studyInstanceUid_ = "";
      patientId_ = "";
      accessionNumber_ = "";
      tenantId_ = "";
      modality_ = "";
      studyDate_ = "";
      objectKey_ = "";
      instanceCount_ = 0;
      reportContent_ = "";
      pathologyConclusion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_IngestStudyRequest_descriptor;
    }

    @java.lang.Override
    public com.mdt.integration.grpc.IngestStudyRequest getDefaultInstanceForType() {
      return com.mdt.integration.grpc.IngestStudyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdt.integration.grpc.IngestStudyRequest build() {
      com.mdt.integration.grpc.IngestStudyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdt.integration.grpc.IngestStudyRequest buildPartial() {
      com.mdt.integration.grpc.IngestStudyRequest result = new com.mdt.integration.grpc.IngestStudyRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mdt.integration.grpc.IngestStudyRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trace_ = traceBuilder_ == null
            ? trace_
            : traceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.studyInstanceUid_ = studyInstanceUid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.patientId_ = patientId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.accessionNumber_ = accessionNumber_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.modality_ = modality_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.studyDate_ = studyDate_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.objectKey_ = objectKey_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.instanceCount_ = instanceCount_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.reportContent_ = reportContent_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.pathologyConclusion_ = pathologyConclusion_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdt.integration.grpc.IngestStudyRequest) {
        return mergeFrom((com.mdt.integration.grpc.IngestStudyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdt.integration.grpc.IngestStudyRequest other) {
      if (other == com.mdt.integration.grpc.IngestStudyRequest.getDefaultInstance()) return this;
      if (other.hasTrace()) {
        mergeTrace(other.getTrace());
      }
      if (!other.getStudyInstanceUid().isEmpty()) {
        studyInstanceUid_ = other.studyInstanceUid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPatientId().isEmpty()) {
        patientId_ = other.patientId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAccessionNumber().isEmpty()) {
        accessionNumber_ = other.accessionNumber_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getModality().isEmpty()) {
        modality_ = other.modality_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getStudyDate().isEmpty()) {
        studyDate_ = other.studyDate_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getObjectKey().isEmpty()) {
        objectKey_ = other.objectKey_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getInstanceCount() != 0) {
        setInstanceCount(other.getInstanceCount());
      }
      if (!other.getReportContent().isEmpty()) {
        reportContent_ = other.reportContent_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getPathologyConclusion().isEmpty()) {
        pathologyConclusion_ = other.pathologyConclusion_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTraceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              studyInstanceUid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              patientId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              accessionNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              modality_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              studyDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              objectKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 72: {
              instanceCount_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 82: {
              reportContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              pathologyConclusion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.mdt.integration.grpc.Trace trace_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder> traceBuilder_;
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     * @return Whether the trace field is set.
     */
    public boolean hasTrace() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     * @return The trace.
     */
    public com.mdt.integration.grpc.Trace getTrace() {
      if (traceBuilder_ == null) {
        return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
      } else {
        return traceBuilder_.getMessage();
      }
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder setTrace(com.mdt.integration.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trace_ = value;
      } else {
        traceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder setTrace(
        com.mdt.integration.grpc.Trace.Builder builderForValue) {
      if (traceBuilder_ == null) {
        trace_ = builderForValue.build();
      } else {
        traceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder mergeTrace(com.mdt.integration.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          trace_ != null &&
          trace_ != com.mdt.integration.grpc.Trace.getDefaultInstance()) {
          getTraceBuilder().mergeFrom(value);
        } else {
          trace_ = value;
        }
      } else {
        traceBuilder_.mergeFrom(value);
      }
      if (trace_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder clearTrace() {
      bitField0_ = (bitField0_ & ~0x00000001);
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public com.mdt.integration.grpc.Trace.Builder getTraceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTraceFieldBuilder().getBuilder();
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder() {
      if (traceBuilder_ != null) {
        return traceBuilder_.getMessageOrBuilder();
      } else {
        return trace_ == null ?
            com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
      }
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder> 
        getTraceFieldBuilder() {
      if (traceBuilder_ == null) {
        traceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder>(
                getTrace(),
                getParentForChildren(),
                isClean());
        trace_ = null;
      }
      return traceBuilder_;
    }

    private java.lang.Object studyInstanceUid_ = "";
    /**
     * <code>string study_instance_uid = 2;</code>
     * @return The studyInstanceUid.
     */
    public java.lang.String getStudyInstanceUid() {
      java.lang.Object ref = studyInstanceUid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studyInstanceUid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string study_instance_uid = 2;</code>
     * @return The bytes for studyInstanceUid.
     */
    public com.google.protobuf.ByteString
        getStudyInstanceUidBytes() {
      java.lang.Object ref = studyInstanceUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studyInstanceUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string study_instance_uid = 2;</code>
     * @param value The studyInstanceUid to set.
     * @return This builder for chaining.
     */
    public Builder setStudyInstanceUid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      studyInstanceUid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string study_instance_uid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyInstanceUid() {
      studyInstanceUid_ = getDefaultInstance().getStudyInstanceUid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string study_instance_uid = 2;</code>
     * @param value The bytes for studyInstanceUid to set.
     * @return This builder for chaining.
     */
    public Builder setStudyInstanceUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      studyInstanceUid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object patientId_ = "";
    /**
     * <code>string patient_id = 3;</code>
     * @return The patientId.
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patient_id = 3;</code>
     * @return The bytes for patientId.
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patient_id = 3;</code>
     * @param value The patientId to set.
     * @return This builder for chaining.
     */
    public Builder setPatientId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      patientId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string patient_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPatientId() {
      patientId_ = getDefaultInstance().getPatientId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string patient_id = 3;</code>
     * @param value The bytes for patientId to set.
     * @return This builder for chaining.
     */
    public Builder setPatientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      patientId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object accessionNumber_ = "";
    /**
     * <code>string accession_number = 4;</code>
     * @return The accessionNumber.
     */
    public java.lang.String getAccessionNumber() {
      java.lang.Object ref = accessionNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessionNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accession_number = 4;</code>
     * @return The bytes for accessionNumber.
     */
    public com.google.protobuf.ByteString
        getAccessionNumberBytes() {
      java.lang.Object ref = accessionNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessionNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accession_number = 4;</code>
     * @param value The accessionNumber to set.
     * @return This builder for chaining.
     */
    public Builder setAccessionNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accessionNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string accession_number = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessionNumber() {
      accessionNumber_ = getDefaultInstance().getAccessionNumber();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string accession_number = 4;</code>
     * @param value The bytes for accessionNumber to set.
     * @return This builder for chaining.
     */
    public Builder setAccessionNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accessionNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 5;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 5;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 5;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 5;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object modality_ = "";
    /**
     * <code>string modality = 6;</code>
     * @return The modality.
     */
    public java.lang.String getModality() {
      java.lang.Object ref = modality_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modality_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string modality = 6;</code>
     * @return The bytes for modality.
     */
    public com.google.protobuf.ByteString
        getModalityBytes() {
      java.lang.Object ref = modality_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string modality = 6;</code>
     * @param value The modality to set.
     * @return This builder for chaining.
     */
    public Builder setModality(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      modality_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string modality = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearModality() {
      modality_ = getDefaultInstance().getModality();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string modality = 6;</code>
     * @param value The bytes for modality to set.
     * @return This builder for chaining.
     */
    public Builder setModalityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      modality_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object studyDate_ = "";
    /**
     * <pre>
     * ISO yyyy-MM-dd
     * </pre>
     *
     * <code>string study_date = 7;</code>
     * @return The studyDate.
     */
    public java.lang.String getStudyDate() {
      java.lang.Object ref = studyDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studyDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ISO yyyy-MM-dd
     * </pre>
     *
     * <code>string study_date = 7;</code>
     * @return The bytes for studyDate.
     */
    public com.google.protobuf.ByteString
        getStudyDateBytes() {
      java.lang.Object ref = studyDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studyDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ISO yyyy-MM-dd
     * </pre>
     *
     * <code>string study_date = 7;</code>
     * @param value The studyDate to set.
     * @return This builder for chaining.
     */
    public Builder setStudyDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      studyDate_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO yyyy-MM-dd
     * </pre>
     *
     * <code>string study_date = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyDate() {
      studyDate_ = getDefaultInstance().getStudyDate();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ISO yyyy-MM-dd
     * </pre>
     *
     * <code>string study_date = 7;</code>
     * @param value The bytes for studyDate to set.
     * @return This builder for chaining.
     */
    public Builder setStudyDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      studyDate_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object objectKey_ = "";
    /**
     * <code>string object_key = 8;</code>
     * @return The objectKey.
     */
    public java.lang.String getObjectKey() {
      java.lang.Object ref = objectKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object_key = 8;</code>
     * @return The bytes for objectKey.
     */
    public com.google.protobuf.ByteString
        getObjectKeyBytes() {
      java.lang.Object ref = objectKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object_key = 8;</code>
     * @param value The objectKey to set.
     * @return This builder for chaining.
     */
    public Builder setObjectKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      objectKey_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string object_key = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectKey() {
      objectKey_ = getDefaultInstance().getObjectKey();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string object_key = 8;</code>
     * @param value The bytes for objectKey to set.
     * @return This builder for chaining.
     */
    public Builder setObjectKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      objectKey_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private int instanceCount_ ;
    /**
     * <code>int32 instance_count = 9;</code>
     * @return The instanceCount.
     */
    @java.lang.Override
    public int getInstanceCount() {
      return instanceCount_;
    }
    /**
     * <code>int32 instance_count = 9;</code>
     * @param value The instanceCount to set.
     * @return This builder for chaining.
     */
    public Builder setInstanceCount(int value) {

      instanceCount_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 instance_count = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstanceCount() {
      bitField0_ = (bitField0_ & ~0x00000100);
      instanceCount_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object reportContent_ = "";
    /**
     * <code>string report_content = 10;</code>
     * @return The reportContent.
     */
    public java.lang.String getReportContent() {
      java.lang.Object ref = reportContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string report_content = 10;</code>
     * @return The bytes for reportContent.
     */
    public com.google.protobuf.ByteString
        getReportContentBytes() {
      java.lang.Object ref = reportContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string report_content = 10;</code>
     * @param value The reportContent to set.
     * @return This builder for chaining.
     */
    public Builder setReportContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reportContent_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string report_content = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearReportContent() {
      reportContent_ = getDefaultInstance().getReportContent();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string report_content = 10;</code>
     * @param value The bytes for reportContent to set.
     * @return This builder for chaining.
     */
    public Builder setReportContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reportContent_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object pathologyConclusion_ = "";
    /**
     * <code>string pathology_conclusion = 11;</code>
     * @return The pathologyConclusion.
     */
    public java.lang.String getPathologyConclusion() {
      java.lang.Object ref = pathologyConclusion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pathologyConclusion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pathology_conclusion = 11;</code>
     * @return The bytes for pathologyConclusion.
     */
    public com.google.protobuf.ByteString
        getPathologyConclusionBytes() {
      java.lang.Object ref = pathologyConclusion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pathologyConclusion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pathology_conclusion = 11;</code>
     * @param value The pathologyConclusion to set.
     * @return This builder for chaining.
     */
    public Builder setPathologyConclusion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pathologyConclusion_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string pathology_conclusion = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPathologyConclusion() {
      pathologyConclusion_ = getDefaultInstance().getPathologyConclusion();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string pathology_conclusion = 11;</code>
     * @param value The bytes for pathologyConclusion to set.
     * @return This builder for chaining.
     */
    public Builder setPathologyConclusionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pathologyConclusion_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mdt.integration.IngestStudyRequest)
  }

  // @@protoc_insertion_point(class_scope:mdt.integration.IngestStudyRequest)
  private static final com.mdt.integration.grpc.IngestStudyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdt.integration.grpc.IngestStudyRequest();
  }

  public static com.mdt.integration.grpc.IngestStudyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IngestStudyRequest>
      PARSER = new com.google.protobuf.AbstractParser<IngestStudyRequest>() {
    @java.lang.Override
    public IngestStudyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IngestStudyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IngestStudyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdt.integration.grpc.IngestStudyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

