// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

public interface IngestStudyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.integration.IngestStudyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return The trace.
   */
  com.mdt.integration.grpc.Trace getTrace();
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   */
  com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder();

  /**
   * <code>string study_instance_uid = 2;</code>
   * @return The studyInstanceUid.
   */
  java.lang.String getStudyInstanceUid();
  /**
   * <code>string study_instance_uid = 2;</code>
   * @return The bytes for studyInstanceUid.
   */
  com.google.protobuf.ByteString
      getStudyInstanceUidBytes();

  /**
   * <code>string patient_id = 3;</code>
   * @return The patientId.
   */
  java.lang.String getPatientId();
  /**
   * <code>string patient_id = 3;</code>
   * @return The bytes for patientId.
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string accession_number = 4;</code>
   * @return The accessionNumber.
   */
  java.lang.String getAccessionNumber();
  /**
   * <code>string accession_number = 4;</code>
   * @return The bytes for accessionNumber.
   */
  com.google.protobuf.ByteString
      getAccessionNumberBytes();

  /**
   * <code>string tenant_id = 5;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 5;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string modality = 6;</code>
   * @return The modality.
   */
  java.lang.String getModality();
  /**
   * <code>string modality = 6;</code>
   * @return The bytes for modality.
   */
  com.google.protobuf.ByteString
      getModalityBytes();

  /**
   * <pre>
   * ISO yyyy-MM-dd
   * </pre>
   *
   * <code>string study_date = 7;</code>
   * @return The studyDate.
   */
  java.lang.String getStudyDate();
  /**
   * <pre>
   * ISO yyyy-MM-dd
   * </pre>
   *
   * <code>string study_date = 7;</code>
   * @return The bytes for studyDate.
   */
  com.google.protobuf.ByteString
      getStudyDateBytes();

  /**
   * <code>string object_key = 8;</code>
   * @return The objectKey.
   */
  java.lang.String getObjectKey();
  /**
   * <code>string object_key = 8;</code>
   * @return The bytes for objectKey.
   */
  com.google.protobuf.ByteString
      getObjectKeyBytes();

  /**
   * <code>int32 instance_count = 9;</code>
   * @return The instanceCount.
   */
  int getInstanceCount();

  /**
   * <code>string report_content = 10;</code>
   * @return The reportContent.
   */
  java.lang.String getReportContent();
  /**
   * <code>string report_content = 10;</code>
   * @return The bytes for reportContent.
   */
  com.google.protobuf.ByteString
      getReportContentBytes();

  /**
   * <code>string pathology_conclusion = 11;</code>
   * @return The pathologyConclusion.
   */
  java.lang.String getPathologyConclusion();
  /**
   * <code>string pathology_conclusion = 11;</code>
   * @return The bytes for pathologyConclusion.
   */
  com.google.protobuf.ByteString
      getPathologyConclusionBytes();
}
