// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

public final class Integration {
  private Integration() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_integration_Trace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_integration_Trace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_integration_PullStudyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_integration_PullStudyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_integration_PullStudyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_integration_PullStudyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_integration_StudyReceivedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_integration_StudyReceivedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_integration_ClinicalDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_integration_ClinicalDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_integration_ClinicalDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_integration_ClinicalDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_integration_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_integration_Ack_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_integration_IngestStudyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_integration_IngestStudyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021integration.proto\022\017mdt.integration\"A\n\005" +
      "Trace\022\020\n\010trace_id\030\001 \001(\t\022\021\n\ttenant_id\030\002 \001" +
      "(\t\022\023\n\013operator_id\030\003 \001(\t\"\200\001\n\020PullStudyReq" +
      "uest\022%\n\005trace\030\001 \001(\0132\026.mdt.integration.Tr" +
      "ace\022\027\n\017called_ae_title\030\002 \001(\t\022\022\n\npatient_" +
      "id\030\003 \001(\t\022\030\n\020accession_number\030\004 \001(\t\"h\n\021Pu" +
      "llStudyResponse\022\017\n\007success\030\001 \001(\010\022\031\n\021pati" +
      "ent_visit_uid\030\002 \001(\t\022\026\n\016instance_count\030\003 " +
      "\001(\005\022\017\n\007message\030\004 \001(\t\"r\n\022StudyReceivedEve" +
      "nt\022%\n\005trace\030\001 \001(\0132\026.mdt.integration.Trac" +
      "e\022\032\n\022study_instance_uid\030\002 \001(\t\022\031\n\021patient" +
      "_visit_uid\030\003 \001(\t\"g\n\023ClinicalDataRequest\022" +
      "%\n\005trace\030\001 \001(\0132\026.mdt.integration.Trace\022\031" +
      "\n\021patient_visit_uid\030\002 \001(\t\022\016\n\006source\030\003 \003(" +
      "\t\"9\n\024ClinicalDataResponse\022\017\n\007success\030\001 \001" +
      "(\010\022\020\n\010emr_json\030\002 \001(\t\"\"\n\003Ack\022\n\n\002ok\030\001 \001(\010\022" +
      "\017\n\007message\030\002 \001(\t\"\240\002\n\022IngestStudyRequest\022" +
      "%\n\005trace\030\001 \001(\0132\026.mdt.integration.Trace\022\032" +
      "\n\022study_instance_uid\030\002 \001(\t\022\022\n\npatient_id" +
      "\030\003 \001(\t\022\030\n\020accession_number\030\004 \001(\t\022\021\n\ttena" +
      "nt_id\030\005 \001(\t\022\020\n\010modality\030\006 \001(\t\022\022\n\nstudy_d" +
      "ate\030\007 \001(\t\022\022\n\nobject_key\030\010 \001(\t\022\026\n\016instanc" +
      "e_count\030\t \001(\005\022\026\n\016report_content\030\n \001(\t\022\034\n" +
      "\024pathology_conclusion\030\013 \001(\t2\352\002\n\022Integrat" +
      "ionService\022Z\n\021PullStudyFromPacs\022!.mdt.in" +
      "tegration.PullStudyRequest\032\".mdt.integra" +
      "tion.PullStudyResponse\022H\n\013IngestStudy\022#." +
      "mdt.integration.IngestStudyRequest\032\024.mdt" +
      ".integration.Ack\022L\n\017OnStudyReceived\022#.md" +
      "t.integration.StudyReceivedEvent\032\024.mdt.i" +
      "ntegration.Ack\022`\n\021FetchClinicalData\022$.md" +
      "t.integration.ClinicalDataRequest\032%.mdt." +
      "integration.ClinicalDataResponseB\034\n\030com." +
      "mdt.integration.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mdt_integration_Trace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mdt_integration_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_integration_Trace_descriptor,
        new java.lang.String[] { "TraceId", "TenantId", "OperatorId", });
    internal_static_mdt_integration_PullStudyRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mdt_integration_PullStudyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_integration_PullStudyRequest_descriptor,
        new java.lang.String[] { "Trace", "CalledAeTitle", "PatientId", "AccessionNumber", });
    internal_static_mdt_integration_PullStudyResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mdt_integration_PullStudyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_integration_PullStudyResponse_descriptor,
        new java.lang.String[] { "Success", "PatientVisitUid", "InstanceCount", "Message", });
    internal_static_mdt_integration_StudyReceivedEvent_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mdt_integration_StudyReceivedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_integration_StudyReceivedEvent_descriptor,
        new java.lang.String[] { "Trace", "StudyInstanceUid", "PatientVisitUid", });
    internal_static_mdt_integration_ClinicalDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mdt_integration_ClinicalDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_integration_ClinicalDataRequest_descriptor,
        new java.lang.String[] { "Trace", "PatientVisitUid", "Source", });
    internal_static_mdt_integration_ClinicalDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mdt_integration_ClinicalDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_integration_ClinicalDataResponse_descriptor,
        new java.lang.String[] { "Success", "EmrJson", });
    internal_static_mdt_integration_Ack_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_mdt_integration_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_integration_Ack_descriptor,
        new java.lang.String[] { "Ok", "Message", });
    internal_static_mdt_integration_IngestStudyRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_mdt_integration_IngestStudyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_integration_IngestStudyRequest_descriptor,
        new java.lang.String[] { "Trace", "StudyInstanceUid", "PatientId", "AccessionNumber", "TenantId", "Modality", "StudyDate", "ObjectKey", "InstanceCount", "ReportContent", "PathologyConclusion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
