// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

public interface PullStudyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.integration.PullStudyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string patient_visit_uid = 2;</code>
   * @return The patientVisitUid.
   */
  java.lang.String getPatientVisitUid();
  /**
   * <code>string patient_visit_uid = 2;</code>
   * @return The bytes for patientVisitUid.
   */
  com.google.protobuf.ByteString
      getPatientVisitUidBytes();

  /**
   * <pre>
   * 拉取到的实例数
   * </pre>
   *
   * <code>int32 instance_count = 3;</code>
   * @return The instanceCount.
   */
  int getInstanceCount();

  /**
   * <code>string message = 4;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
