// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

public interface PullStudyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.integration.PullStudyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return The trace.
   */
  com.mdt.integration.grpc.Trace getTrace();
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   */
  com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder();

  /**
   * <pre>
   * 对端 PACS AE Title
   * </pre>
   *
   * <code>string called_ae_title = 2;</code>
   * @return The calledAeTitle.
   */
  java.lang.String getCalledAeTitle();
  /**
   * <pre>
   * 对端 PACS AE Title
   * </pre>
   *
   * <code>string called_ae_title = 2;</code>
   * @return The bytes for calledAeTitle.
   */
  com.google.protobuf.ByteString
      getCalledAeTitleBytes();

  /**
   * <code>string patient_id = 3;</code>
   * @return The patientId.
   */
  java.lang.String getPatientId();
  /**
   * <code>string patient_id = 3;</code>
   * @return The bytes for patientId.
   */
  com.google.protobuf.ByteString
      getPatientIdBytes();

  /**
   * <code>string accession_number = 4;</code>
   * @return The accessionNumber.
   */
  java.lang.String getAccessionNumber();
  /**
   * <code>string accession_number = 4;</code>
   * @return The bytes for accessionNumber.
   */
  com.google.protobuf.ByteString
      getAccessionNumberBytes();
}
