// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

/**
 * <pre>
 * 从 PACS 经 SCU 拉取某次检查全序列影像（C-FIND -&gt; C-MOVE）
 * </pre>
 *
 * Protobuf type {@code mdt.integration.PullStudyRequest}
 */
public final class PullStudyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mdt.integration.PullStudyRequest)
    PullStudyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PullStudyRequest.newBuilder() to construct.
  private PullStudyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PullStudyRequest() {
    calledAeTitle_ = "";
    patientId_ = "";
    accessionNumber_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PullStudyRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_PullStudyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_PullStudyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdt.integration.grpc.PullStudyRequest.class, com.mdt.integration.grpc.PullStudyRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TRACE_FIELD_NUMBER = 1;
  private com.mdt.integration.grpc.Trace trace_;
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  @java.lang.Override
  public boolean hasTrace() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return The trace.
   */
  @java.lang.Override
  public com.mdt.integration.grpc.Trace getTrace() {
    return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
  }
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   */
  @java.lang.Override
  public com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder() {
    return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
  }

  public static final int CALLED_AE_TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object calledAeTitle_ = "";
  /**
   * <pre>
   * 对端 PACS AE Title
   * </pre>
   *
   * <code>string called_ae_title = 2;</code>
   * @return The calledAeTitle.
   */
  @java.lang.Override
  public java.lang.String getCalledAeTitle() {
    java.lang.Object ref = calledAeTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      calledAeTitle_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 对端 PACS AE Title
   * </pre>
   *
   * <code>string called_ae_title = 2;</code>
   * @return The bytes for calledAeTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCalledAeTitleBytes() {
    java.lang.Object ref = calledAeTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      calledAeTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATIENT_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object patientId_ = "";
  /**
   * <code>string patient_id = 3;</code>
   * @return The patientId.
   */
  @java.lang.Override
  public java.lang.String getPatientId() {
    java.lang.Object ref = patientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patientId_ = s;
      return s;
    }
  }
  /**
   * <code>string patient_id = 3;</code>
   * @return The bytes for patientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPatientIdBytes() {
    java.lang.Object ref = patientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCESSION_NUMBER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accessionNumber_ = "";
  /**
   * <code>string accession_number = 4;</code>
   * @return The accessionNumber.
   */
  @java.lang.Override
  public java.lang.String getAccessionNumber() {
    java.lang.Object ref = accessionNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessionNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string accession_number = 4;</code>
   * @return The bytes for accessionNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccessionNumberBytes() {
    java.lang.Object ref = accessionNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessionNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(calledAeTitle_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, calledAeTitle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, patientId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessionNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accessionNumber_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(calledAeTitle_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, calledAeTitle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, patientId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessionNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accessionNumber_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdt.integration.grpc.PullStudyRequest)) {
      return super.equals(obj);
    }
    com.mdt.integration.grpc.PullStudyRequest other = (com.mdt.integration.grpc.PullStudyRequest) obj;

    if (hasTrace() != other.hasTrace()) return false;
    if (hasTrace()) {
      if (!getTrace()
          .equals(other.getTrace())) return false;
    }
    if (!getCalledAeTitle()
        .equals(other.getCalledAeTitle())) return false;
    if (!getPatientId()
        .equals(other.getPatientId())) return false;
    if (!getAccessionNumber()
        .equals(other.getAccessionNumber())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTrace()) {
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace().hashCode();
    }
    hash = (37 * hash) + CALLED_AE_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getCalledAeTitle().hashCode();
    hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientId().hashCode();
    hash = (37 * hash) + ACCESSION_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getAccessionNumber().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mdt.integration.grpc.PullStudyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mdt.integration.grpc.PullStudyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.integration.grpc.PullStudyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdt.integration.grpc.PullStudyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 从 PACS 经 SCU 拉取某次检查全序列影像（C-FIND -&gt; C-MOVE）
   * </pre>
   *
   * Protobuf type {@code mdt.integration.PullStudyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mdt.integration.PullStudyRequest)
      com.mdt.integration.grpc.PullStudyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_PullStudyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_PullStudyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdt.integration.grpc.PullStudyRequest.class, com.mdt.integration.grpc.PullStudyRequest.Builder.class);
    }

    // Construct using com.mdt.integration.grpc.PullStudyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      calledAeTitle_ = "";
      patientId_ = "";
      accessionNumber_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_PullStudyRequest_descriptor;
    }

    @java.lang.Override
    public com.mdt.integration.grpc.PullStudyRequest getDefaultInstanceForType() {
      return com.mdt.integration.grpc.PullStudyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdt.integration.grpc.PullStudyRequest build() {
      com.mdt.integration.grpc.PullStudyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdt.integration.grpc.PullStudyRequest buildPartial() {
      com.mdt.integration.grpc.PullStudyRequest result = new com.mdt.integration.grpc.PullStudyRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mdt.integration.grpc.PullStudyRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trace_ = traceBuilder_ == null
            ? trace_
            : traceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.calledAeTitle_ = calledAeTitle_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.patientId_ = patientId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.accessionNumber_ = accessionNumber_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdt.integration.grpc.PullStudyRequest) {
        return mergeFrom((com.mdt.integration.grpc.PullStudyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdt.integration.grpc.PullStudyRequest other) {
      if (other == com.mdt.integration.grpc.PullStudyRequest.getDefaultInstance()) return this;
      if (other.hasTrace()) {
        mergeTrace(other.getTrace());
      }
      if (!other.getCalledAeTitle().isEmpty()) {
        calledAeTitle_ = other.calledAeTitle_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPatientId().isEmpty()) {
        patientId_ = other.patientId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAccessionNumber().isEmpty()) {
        accessionNumber_ = other.accessionNumber_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTraceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              calledAeTitle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              patientId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              accessionNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.mdt.integration.grpc.Trace trace_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder> traceBuilder_;
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     * @return Whether the trace field is set.
     */
    public boolean hasTrace() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     * @return The trace.
     */
    public com.mdt.integration.grpc.Trace getTrace() {
      if (traceBuilder_ == null) {
        return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
      } else {
        return traceBuilder_.getMessage();
      }
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder setTrace(com.mdt.integration.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trace_ = value;
      } else {
        traceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder setTrace(
        com.mdt.integration.grpc.Trace.Builder builderForValue) {
      if (traceBuilder_ == null) {
        trace_ = builderForValue.build();
      } else {
        traceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder mergeTrace(com.mdt.integration.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          trace_ != null &&
          trace_ != com.mdt.integration.grpc.Trace.getDefaultInstance()) {
          getTraceBuilder().mergeFrom(value);
        } else {
          trace_ = value;
        }
      } else {
        traceBuilder_.mergeFrom(value);
      }
      if (trace_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder clearTrace() {
      bitField0_ = (bitField0_ & ~0x00000001);
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public com.mdt.integration.grpc.Trace.Builder getTraceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTraceFieldBuilder().getBuilder();
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder() {
      if (traceBuilder_ != null) {
        return traceBuilder_.getMessageOrBuilder();
      } else {
        return trace_ == null ?
            com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
      }
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder> 
        getTraceFieldBuilder() {
      if (traceBuilder_ == null) {
        traceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder>(
                getTrace(),
                getParentForChildren(),
                isClean());
        trace_ = null;
      }
      return traceBuilder_;
    }

    private java.lang.Object calledAeTitle_ = "";
    /**
     * <pre>
     * 对端 PACS AE Title
     * </pre>
     *
     * <code>string called_ae_title = 2;</code>
     * @return The calledAeTitle.
     */
    public java.lang.String getCalledAeTitle() {
      java.lang.Object ref = calledAeTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        calledAeTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 对端 PACS AE Title
     * </pre>
     *
     * <code>string called_ae_title = 2;</code>
     * @return The bytes for calledAeTitle.
     */
    public com.google.protobuf.ByteString
        getCalledAeTitleBytes() {
      java.lang.Object ref = calledAeTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        calledAeTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 对端 PACS AE Title
     * </pre>
     *
     * <code>string called_ae_title = 2;</code>
     * @param value The calledAeTitle to set.
     * @return This builder for chaining.
     */
    public Builder setCalledAeTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      calledAeTitle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对端 PACS AE Title
     * </pre>
     *
     * <code>string called_ae_title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCalledAeTitle() {
      calledAeTitle_ = getDefaultInstance().getCalledAeTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 对端 PACS AE Title
     * </pre>
     *
     * <code>string called_ae_title = 2;</code>
     * @param value The bytes for calledAeTitle to set.
     * @return This builder for chaining.
     */
    public Builder setCalledAeTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      calledAeTitle_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object patientId_ = "";
    /**
     * <code>string patient_id = 3;</code>
     * @return The patientId.
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patient_id = 3;</code>
     * @return The bytes for patientId.
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patient_id = 3;</code>
     * @param value The patientId to set.
     * @return This builder for chaining.
     */
    public Builder setPatientId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      patientId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string patient_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPatientId() {
      patientId_ = getDefaultInstance().getPatientId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string patient_id = 3;</code>
     * @param value The bytes for patientId to set.
     * @return This builder for chaining.
     */
    public Builder setPatientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      patientId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object accessionNumber_ = "";
    /**
     * <code>string accession_number = 4;</code>
     * @return The accessionNumber.
     */
    public java.lang.String getAccessionNumber() {
      java.lang.Object ref = accessionNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessionNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accession_number = 4;</code>
     * @return The bytes for accessionNumber.
     */
    public com.google.protobuf.ByteString
        getAccessionNumberBytes() {
      java.lang.Object ref = accessionNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessionNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accession_number = 4;</code>
     * @param value The accessionNumber to set.
     * @return This builder for chaining.
     */
    public Builder setAccessionNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accessionNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string accession_number = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessionNumber() {
      accessionNumber_ = getDefaultInstance().getAccessionNumber();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string accession_number = 4;</code>
     * @param value The bytes for accessionNumber to set.
     * @return This builder for chaining.
     */
    public Builder setAccessionNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accessionNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mdt.integration.PullStudyRequest)
  }

  // @@protoc_insertion_point(class_scope:mdt.integration.PullStudyRequest)
  private static final com.mdt.integration.grpc.PullStudyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdt.integration.grpc.PullStudyRequest();
  }

  public static com.mdt.integration.grpc.PullStudyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PullStudyRequest>
      PARSER = new com.google.protobuf.AbstractParser<PullStudyRequest>() {
    @java.lang.Override
    public PullStudyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PullStudyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PullStudyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdt.integration.grpc.PullStudyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

