// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

/**
 * <pre>
 * 接收设备经 SCP 推送的影像（内部由 DICOM SCP 触发，落库后回调）
 * </pre>
 *
 * Protobuf type {@code mdt.integration.StudyReceivedEvent}
 */
public final class StudyReceivedEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mdt.integration.StudyReceivedEvent)
    StudyReceivedEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudyReceivedEvent.newBuilder() to construct.
  private StudyReceivedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudyReceivedEvent() {
    studyInstanceUid_ = "";
    patientVisitUid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StudyReceivedEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_StudyReceivedEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_StudyReceivedEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdt.integration.grpc.StudyReceivedEvent.class, com.mdt.integration.grpc.StudyReceivedEvent.Builder.class);
  }

  private int bitField0_;
  public static final int TRACE_FIELD_NUMBER = 1;
  private com.mdt.integration.grpc.Trace trace_;
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  @java.lang.Override
  public boolean hasTrace() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return The trace.
   */
  @java.lang.Override
  public com.mdt.integration.grpc.Trace getTrace() {
    return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
  }
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   */
  @java.lang.Override
  public com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder() {
    return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
  }

  public static final int STUDY_INSTANCE_UID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object studyInstanceUid_ = "";
  /**
   * <code>string study_instance_uid = 2;</code>
   * @return The studyInstanceUid.
   */
  @java.lang.Override
  public java.lang.String getStudyInstanceUid() {
    java.lang.Object ref = studyInstanceUid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studyInstanceUid_ = s;
      return s;
    }
  }
  /**
   * <code>string study_instance_uid = 2;</code>
   * @return The bytes for studyInstanceUid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStudyInstanceUidBytes() {
    java.lang.Object ref = studyInstanceUid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studyInstanceUid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATIENT_VISIT_UID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object patientVisitUid_ = "";
  /**
   * <code>string patient_visit_uid = 3;</code>
   * @return The patientVisitUid.
   */
  @java.lang.Override
  public java.lang.String getPatientVisitUid() {
    java.lang.Object ref = patientVisitUid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patientVisitUid_ = s;
      return s;
    }
  }
  /**
   * <code>string patient_visit_uid = 3;</code>
   * @return The bytes for patientVisitUid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPatientVisitUidBytes() {
    java.lang.Object ref = patientVisitUid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patientVisitUid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(studyInstanceUid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, studyInstanceUid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientVisitUid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, patientVisitUid_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(studyInstanceUid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, studyInstanceUid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientVisitUid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, patientVisitUid_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdt.integration.grpc.StudyReceivedEvent)) {
      return super.equals(obj);
    }
    com.mdt.integration.grpc.StudyReceivedEvent other = (com.mdt.integration.grpc.StudyReceivedEvent) obj;

    if (hasTrace() != other.hasTrace()) return false;
    if (hasTrace()) {
      if (!getTrace()
          .equals(other.getTrace())) return false;
    }
    if (!getStudyInstanceUid()
        .equals(other.getStudyInstanceUid())) return false;
    if (!getPatientVisitUid()
        .equals(other.getPatientVisitUid())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTrace()) {
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace().hashCode();
    }
    hash = (37 * hash) + STUDY_INSTANCE_UID_FIELD_NUMBER;
    hash = (53 * hash) + getStudyInstanceUid().hashCode();
    hash = (37 * hash) + PATIENT_VISIT_UID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientVisitUid().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mdt.integration.grpc.StudyReceivedEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mdt.integration.grpc.StudyReceivedEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.integration.grpc.StudyReceivedEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdt.integration.grpc.StudyReceivedEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 接收设备经 SCP 推送的影像（内部由 DICOM SCP 触发，落库后回调）
   * </pre>
   *
   * Protobuf type {@code mdt.integration.StudyReceivedEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mdt.integration.StudyReceivedEvent)
      com.mdt.integration.grpc.StudyReceivedEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_StudyReceivedEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_StudyReceivedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdt.integration.grpc.StudyReceivedEvent.class, com.mdt.integration.grpc.StudyReceivedEvent.Builder.class);
    }

    // Construct using com.mdt.integration.grpc.StudyReceivedEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      studyInstanceUid_ = "";
      patientVisitUid_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdt.integration.grpc.Integration.internal_static_mdt_integration_StudyReceivedEvent_descriptor;
    }

    @java.lang.Override
    public com.mdt.integration.grpc.StudyReceivedEvent getDefaultInstanceForType() {
      return com.mdt.integration.grpc.StudyReceivedEvent.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdt.integration.grpc.StudyReceivedEvent build() {
      com.mdt.integration.grpc.StudyReceivedEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdt.integration.grpc.StudyReceivedEvent buildPartial() {
      com.mdt.integration.grpc.StudyReceivedEvent result = new com.mdt.integration.grpc.StudyReceivedEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mdt.integration.grpc.StudyReceivedEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trace_ = traceBuilder_ == null
            ? trace_
            : traceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.studyInstanceUid_ = studyInstanceUid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.patientVisitUid_ = patientVisitUid_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdt.integration.grpc.StudyReceivedEvent) {
        return mergeFrom((com.mdt.integration.grpc.StudyReceivedEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdt.integration.grpc.StudyReceivedEvent other) {
      if (other == com.mdt.integration.grpc.StudyReceivedEvent.getDefaultInstance()) return this;
      if (other.hasTrace()) {
        mergeTrace(other.getTrace());
      }
      if (!other.getStudyInstanceUid().isEmpty()) {
        studyInstanceUid_ = other.studyInstanceUid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPatientVisitUid().isEmpty()) {
        patientVisitUid_ = other.patientVisitUid_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTraceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              studyInstanceUid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              patientVisitUid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.mdt.integration.grpc.Trace trace_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder> traceBuilder_;
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     * @return Whether the trace field is set.
     */
    public boolean hasTrace() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     * @return The trace.
     */
    public com.mdt.integration.grpc.Trace getTrace() {
      if (traceBuilder_ == null) {
        return trace_ == null ? com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
      } else {
        return traceBuilder_.getMessage();
      }
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder setTrace(com.mdt.integration.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trace_ = value;
      } else {
        traceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder setTrace(
        com.mdt.integration.grpc.Trace.Builder builderForValue) {
      if (traceBuilder_ == null) {
        trace_ = builderForValue.build();
      } else {
        traceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder mergeTrace(com.mdt.integration.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          trace_ != null &&
          trace_ != com.mdt.integration.grpc.Trace.getDefaultInstance()) {
          getTraceBuilder().mergeFrom(value);
        } else {
          trace_ = value;
        }
      } else {
        traceBuilder_.mergeFrom(value);
      }
      if (trace_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public Builder clearTrace() {
      bitField0_ = (bitField0_ & ~0x00000001);
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public com.mdt.integration.grpc.Trace.Builder getTraceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTraceFieldBuilder().getBuilder();
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    public com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder() {
      if (traceBuilder_ != null) {
        return traceBuilder_.getMessageOrBuilder();
      } else {
        return trace_ == null ?
            com.mdt.integration.grpc.Trace.getDefaultInstance() : trace_;
      }
    }
    /**
     * <code>.mdt.integration.Trace trace = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder> 
        getTraceFieldBuilder() {
      if (traceBuilder_ == null) {
        traceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mdt.integration.grpc.Trace, com.mdt.integration.grpc.Trace.Builder, com.mdt.integration.grpc.TraceOrBuilder>(
                getTrace(),
                getParentForChildren(),
                isClean());
        trace_ = null;
      }
      return traceBuilder_;
    }

    private java.lang.Object studyInstanceUid_ = "";
    /**
     * <code>string study_instance_uid = 2;</code>
     * @return The studyInstanceUid.
     */
    public java.lang.String getStudyInstanceUid() {
      java.lang.Object ref = studyInstanceUid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studyInstanceUid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string study_instance_uid = 2;</code>
     * @return The bytes for studyInstanceUid.
     */
    public com.google.protobuf.ByteString
        getStudyInstanceUidBytes() {
      java.lang.Object ref = studyInstanceUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studyInstanceUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string study_instance_uid = 2;</code>
     * @param value The studyInstanceUid to set.
     * @return This builder for chaining.
     */
    public Builder setStudyInstanceUid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      studyInstanceUid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string study_instance_uid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStudyInstanceUid() {
      studyInstanceUid_ = getDefaultInstance().getStudyInstanceUid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string study_instance_uid = 2;</code>
     * @param value The bytes for studyInstanceUid to set.
     * @return This builder for chaining.
     */
    public Builder setStudyInstanceUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      studyInstanceUid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object patientVisitUid_ = "";
    /**
     * <code>string patient_visit_uid = 3;</code>
     * @return The patientVisitUid.
     */
    public java.lang.String getPatientVisitUid() {
      java.lang.Object ref = patientVisitUid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientVisitUid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patient_visit_uid = 3;</code>
     * @return The bytes for patientVisitUid.
     */
    public com.google.protobuf.ByteString
        getPatientVisitUidBytes() {
      java.lang.Object ref = patientVisitUid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientVisitUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patient_visit_uid = 3;</code>
     * @param value The patientVisitUid to set.
     * @return This builder for chaining.
     */
    public Builder setPatientVisitUid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      patientVisitUid_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string patient_visit_uid = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPatientVisitUid() {
      patientVisitUid_ = getDefaultInstance().getPatientVisitUid();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string patient_visit_uid = 3;</code>
     * @param value The bytes for patientVisitUid to set.
     * @return This builder for chaining.
     */
    public Builder setPatientVisitUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      patientVisitUid_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mdt.integration.StudyReceivedEvent)
  }

  // @@protoc_insertion_point(class_scope:mdt.integration.StudyReceivedEvent)
  private static final com.mdt.integration.grpc.StudyReceivedEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdt.integration.grpc.StudyReceivedEvent();
  }

  public static com.mdt.integration.grpc.StudyReceivedEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudyReceivedEvent>
      PARSER = new com.google.protobuf.AbstractParser<StudyReceivedEvent>() {
    @java.lang.Override
    public StudyReceivedEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StudyReceivedEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudyReceivedEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdt.integration.grpc.StudyReceivedEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

