// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

public interface StudyReceivedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.integration.StudyReceivedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   * @return The trace.
   */
  com.mdt.integration.grpc.Trace getTrace();
  /**
   * <code>.mdt.integration.Trace trace = 1;</code>
   */
  com.mdt.integration.grpc.TraceOrBuilder getTraceOrBuilder();

  /**
   * <code>string study_instance_uid = 2;</code>
   * @return The studyInstanceUid.
   */
  java.lang.String getStudyInstanceUid();
  /**
   * <code>string study_instance_uid = 2;</code>
   * @return The bytes for studyInstanceUid.
   */
  com.google.protobuf.ByteString
      getStudyInstanceUidBytes();

  /**
   * <code>string patient_visit_uid = 3;</code>
   * @return The patientVisitUid.
   */
  java.lang.String getPatientVisitUid();
  /**
   * <code>string patient_visit_uid = 3;</code>
   * @return The bytes for patientVisitUid.
   */
  com.google.protobuf.ByteString
      getPatientVisitUidBytes();
}
