// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: integration.proto

// Protobuf Java Version: 3.25.3
package com.mdt.integration.grpc;

public interface TraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.integration.Trace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 全链路追踪 ID（网关注入）
   * </pre>
   *
   * <code>string trace_id = 1;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <pre>
   * 全链路追踪 ID（网关注入）
   * </pre>
   *
   * <code>string trace_id = 1;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <pre>
   * 租户（医疗机构）ID，多租户隔离
   * </pre>
   *
   * <code>string tenant_id = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   * 租户（医疗机构）ID，多租户隔离
   * </pre>
   *
   * <code>string tenant_id = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   * 操作人 ID
   * </pre>
   *
   * <code>string operator_id = 3;</code>
   * @return The operatorId.
   */
  java.lang.String getOperatorId();
  /**
   * <pre>
   * 操作人 ID
   * </pre>
   *
   * <code>string operator_id = 3;</code>
   * @return The bytes for operatorId.
   */
  com.google.protobuf.ByteString
      getOperatorIdBytes();
}
