// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collab.proto

// Protobuf Java Version: 3.25.1
package com.mdt.collab.grpc;

public interface AckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.collab.Ack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
