// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collab.proto

// Protobuf Java Version: 3.25.1
package com.mdt.collab.grpc;

public interface AnnotationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.collab.AnnotationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   * @return The trace.
   */
  com.mdt.collab.grpc.Trace getTrace();
  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   */
  com.mdt.collab.grpc.TraceOrBuilder getTraceOrBuilder();

  /**
   * <code>string consultation_id = 2;</code>
   * @return The consultationId.
   */
  java.lang.String getConsultationId();
  /**
   * <code>string consultation_id = 2;</code>
   * @return The bytes for consultationId.
   */
  com.google.protobuf.ByteString
      getConsultationIdBytes();

  /**
   * <code>string element_id = 3;</code>
   * @return The elementId.
   */
  java.lang.String getElementId();
  /**
   * <code>string element_id = 3;</code>
   * @return The bytes for elementId.
   */
  com.google.protobuf.ByteString
      getElementIdBytes();

  /**
   * <pre>
   * 序列化后的标注（JSON/Protobuf）
   * </pre>
   *
   * <code>bytes payload = 4;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <pre>
   * 乐观锁版本号
   * </pre>
   *
   * <code>int64 version = 5;</code>
   * @return The version.
   */
  long getVersion();
}
