// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collab.proto

// Protobuf Java Version: 3.25.1
package com.mdt.collab.grpc;

public final class Collab {
  private Collab() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_collab_Trace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_collab_Trace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_collab_JoinRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_collab_JoinRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_collab_JoinRoomResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_collab_JoinRoomResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_collab_AnnotationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_collab_AnnotationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_collab_QualityReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_collab_QualityReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_collab_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_collab_Ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014collab.proto\022\nmdt.collab\"A\n\005Trace\022\020\n\010t" +
      "race_id\030\001 \001(\t\022\021\n\ttenant_id\030\002 \001(\t\022\023\n\013oper" +
      "ator_id\030\003 \001(\t\"]\n\017JoinRoomRequest\022 \n\005trac" +
      "e\030\001 \001(\0132\021.mdt.collab.Trace\022\027\n\017consultati" +
      "on_id\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\t\"<\n\020JoinRoom" +
      "Response\022\024\n\014sfu_endpoint\030\001 \001(\t\022\022\n\nroom_t" +
      "oken\030\002 \001(\t\"\204\001\n\021AnnotationMessage\022 \n\005trac" +
      "e\030\001 \001(\0132\021.mdt.collab.Trace\022\027\n\017consultati" +
      "on_id\030\002 \001(\t\022\022\n\nelement_id\030\003 \001(\t\022\017\n\007paylo" +
      "ad\030\004 \001(\014\022\017\n\007version\030\005 \001(\003\"t\n\rQualityRepo" +
      "rt\022 \n\005trace\030\001 \001(\0132\021.mdt.collab.Trace\022\027\n\017" +
      "consultation_id\030\002 \001(\t\022\023\n\013uplink_kbps\030\003 \001" +
      "(\005\022\023\n\013packet_loss\030\004 \001(\005\"\"\n\003Ack\022\n\n\002ok\030\001 \001" +
      "(\010\022\017\n\007message\030\002 \001(\t2\325\001\n\rCollabService\022E\n" +
      "\010JoinRoom\022\033.mdt.collab.JoinRoomRequest\032\034" +
      ".mdt.collab.JoinRoomResponse\022@\n\016PushAnno" +
      "tation\022\035.mdt.collab.AnnotationMessage\032\017." +
      "mdt.collab.Ack\022;\n\rReportQuality\022\031.mdt.co" +
      "llab.QualityReport\032\017.mdt.collab.AckB\027\n\023c" +
      "om.mdt.collab.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mdt_collab_Trace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mdt_collab_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_collab_Trace_descriptor,
        new java.lang.String[] { "TraceId", "TenantId", "OperatorId", });
    internal_static_mdt_collab_JoinRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mdt_collab_JoinRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_collab_JoinRoomRequest_descriptor,
        new java.lang.String[] { "Trace", "ConsultationId", "UserId", });
    internal_static_mdt_collab_JoinRoomResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mdt_collab_JoinRoomResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_collab_JoinRoomResponse_descriptor,
        new java.lang.String[] { "SfuEndpoint", "RoomToken", });
    internal_static_mdt_collab_AnnotationMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mdt_collab_AnnotationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_collab_AnnotationMessage_descriptor,
        new java.lang.String[] { "Trace", "ConsultationId", "ElementId", "Payload", "Version", });
    internal_static_mdt_collab_QualityReport_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_mdt_collab_QualityReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_collab_QualityReport_descriptor,
        new java.lang.String[] { "Trace", "ConsultationId", "UplinkKbps", "PacketLoss", });
    internal_static_mdt_collab_Ack_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_mdt_collab_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_collab_Ack_descriptor,
        new java.lang.String[] { "Ok", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
