// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collab.proto

// Protobuf Java Version: 3.25.1
package com.mdt.collab.grpc;

public interface JoinRoomResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.collab.JoinRoomResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
   * </pre>
   *
   * <code>string sfu_endpoint = 1;</code>
   * @return The sfuEndpoint.
   */
  java.lang.String getSfuEndpoint();
  /**
   * <pre>
   * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
   * </pre>
   *
   * <code>string sfu_endpoint = 1;</code>
   * @return The bytes for sfuEndpoint.
   */
  com.google.protobuf.ByteString
      getSfuEndpointBytes();

  /**
   * <code>string room_token = 2;</code>
   * @return The roomToken.
   */
  java.lang.String getRoomToken();
  /**
   * <code>string room_token = 2;</code>
   * @return The bytes for roomToken.
   */
  com.google.protobuf.ByteString
      getRoomTokenBytes();
}
