// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collab.proto

// Protobuf Java Version: 3.25.1
package com.mdt.collab.grpc;

/**
 * Protobuf type {@code mdt.collab.JoinRoomResponse}
 */
public final class JoinRoomResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mdt.collab.JoinRoomResponse)
    JoinRoomResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JoinRoomResponse.newBuilder() to construct.
  private JoinRoomResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JoinRoomResponse() {
    sfuEndpoint_ = "";
    roomToken_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JoinRoomResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_JoinRoomResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_JoinRoomResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdt.collab.grpc.JoinRoomResponse.class, com.mdt.collab.grpc.JoinRoomResponse.Builder.class);
  }

  public static final int SFU_ENDPOINT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sfuEndpoint_ = "";
  /**
   * <pre>
   * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
   * </pre>
   *
   * <code>string sfu_endpoint = 1;</code>
   * @return The sfuEndpoint.
   */
  @java.lang.Override
  public java.lang.String getSfuEndpoint() {
    java.lang.Object ref = sfuEndpoint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sfuEndpoint_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
   * </pre>
   *
   * <code>string sfu_endpoint = 1;</code>
   * @return The bytes for sfuEndpoint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSfuEndpointBytes() {
    java.lang.Object ref = sfuEndpoint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sfuEndpoint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOM_TOKEN_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object roomToken_ = "";
  /**
   * <code>string room_token = 2;</code>
   * @return The roomToken.
   */
  @java.lang.Override
  public java.lang.String getRoomToken() {
    java.lang.Object ref = roomToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomToken_ = s;
      return s;
    }
  }
  /**
   * <code>string room_token = 2;</code>
   * @return The bytes for roomToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRoomTokenBytes() {
    java.lang.Object ref = roomToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sfuEndpoint_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sfuEndpoint_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sfuEndpoint_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sfuEndpoint_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdt.collab.grpc.JoinRoomResponse)) {
      return super.equals(obj);
    }
    com.mdt.collab.grpc.JoinRoomResponse other = (com.mdt.collab.grpc.JoinRoomResponse) obj;

    if (!getSfuEndpoint()
        .equals(other.getSfuEndpoint())) return false;
    if (!getRoomToken()
        .equals(other.getRoomToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SFU_ENDPOINT_FIELD_NUMBER;
    hash = (53 * hash) + getSfuEndpoint().hashCode();
    hash = (37 * hash) + ROOM_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getRoomToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mdt.collab.grpc.JoinRoomResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mdt.collab.grpc.JoinRoomResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.collab.grpc.JoinRoomResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdt.collab.grpc.JoinRoomResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mdt.collab.JoinRoomResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mdt.collab.JoinRoomResponse)
      com.mdt.collab.grpc.JoinRoomResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_JoinRoomResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_JoinRoomResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdt.collab.grpc.JoinRoomResponse.class, com.mdt.collab.grpc.JoinRoomResponse.Builder.class);
    }

    // Construct using com.mdt.collab.grpc.JoinRoomResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sfuEndpoint_ = "";
      roomToken_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_JoinRoomResponse_descriptor;
    }

    @java.lang.Override
    public com.mdt.collab.grpc.JoinRoomResponse getDefaultInstanceForType() {
      return com.mdt.collab.grpc.JoinRoomResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdt.collab.grpc.JoinRoomResponse build() {
      com.mdt.collab.grpc.JoinRoomResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdt.collab.grpc.JoinRoomResponse buildPartial() {
      com.mdt.collab.grpc.JoinRoomResponse result = new com.mdt.collab.grpc.JoinRoomResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mdt.collab.grpc.JoinRoomResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sfuEndpoint_ = sfuEndpoint_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.roomToken_ = roomToken_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdt.collab.grpc.JoinRoomResponse) {
        return mergeFrom((com.mdt.collab.grpc.JoinRoomResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdt.collab.grpc.JoinRoomResponse other) {
      if (other == com.mdt.collab.grpc.JoinRoomResponse.getDefaultInstance()) return this;
      if (!other.getSfuEndpoint().isEmpty()) {
        sfuEndpoint_ = other.sfuEndpoint_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRoomToken().isEmpty()) {
        roomToken_ = other.roomToken_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sfuEndpoint_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              roomToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sfuEndpoint_ = "";
    /**
     * <pre>
     * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
     * </pre>
     *
     * <code>string sfu_endpoint = 1;</code>
     * @return The sfuEndpoint.
     */
    public java.lang.String getSfuEndpoint() {
      java.lang.Object ref = sfuEndpoint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sfuEndpoint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
     * </pre>
     *
     * <code>string sfu_endpoint = 1;</code>
     * @return The bytes for sfuEndpoint.
     */
    public com.google.protobuf.ByteString
        getSfuEndpointBytes() {
      java.lang.Object ref = sfuEndpoint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sfuEndpoint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
     * </pre>
     *
     * <code>string sfu_endpoint = 1;</code>
     * @param value The sfuEndpoint to set.
     * @return This builder for chaining.
     */
    public Builder setSfuEndpoint(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sfuEndpoint_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
     * </pre>
     *
     * <code>string sfu_endpoint = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSfuEndpoint() {
      sfuEndpoint_ = getDefaultInstance().getSfuEndpoint();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 研发态 = WS 信令地址；生产 = 真实 SFU 媒体地址
     * </pre>
     *
     * <code>string sfu_endpoint = 1;</code>
     * @param value The bytes for sfuEndpoint to set.
     * @return This builder for chaining.
     */
    public Builder setSfuEndpointBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sfuEndpoint_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object roomToken_ = "";
    /**
     * <code>string room_token = 2;</code>
     * @return The roomToken.
     */
    public java.lang.String getRoomToken() {
      java.lang.Object ref = roomToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string room_token = 2;</code>
     * @return The bytes for roomToken.
     */
    public com.google.protobuf.ByteString
        getRoomTokenBytes() {
      java.lang.Object ref = roomToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string room_token = 2;</code>
     * @param value The roomToken to set.
     * @return This builder for chaining.
     */
    public Builder setRoomToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      roomToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string room_token = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoomToken() {
      roomToken_ = getDefaultInstance().getRoomToken();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string room_token = 2;</code>
     * @param value The bytes for roomToken to set.
     * @return This builder for chaining.
     */
    public Builder setRoomTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      roomToken_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mdt.collab.JoinRoomResponse)
  }

  // @@protoc_insertion_point(class_scope:mdt.collab.JoinRoomResponse)
  private static final com.mdt.collab.grpc.JoinRoomResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdt.collab.grpc.JoinRoomResponse();
  }

  public static com.mdt.collab.grpc.JoinRoomResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinRoomResponse>
      PARSER = new com.google.protobuf.AbstractParser<JoinRoomResponse>() {
    @java.lang.Override
    public JoinRoomResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JoinRoomResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JoinRoomResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdt.collab.grpc.JoinRoomResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

