// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collab.proto

// Protobuf Java Version: 3.25.1
package com.mdt.collab.grpc;

public interface QualityReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.collab.QualityReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  boolean hasTrace();
  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   * @return The trace.
   */
  com.mdt.collab.grpc.Trace getTrace();
  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   */
  com.mdt.collab.grpc.TraceOrBuilder getTraceOrBuilder();

  /**
   * <code>string consultation_id = 2;</code>
   * @return The consultationId.
   */
  java.lang.String getConsultationId();
  /**
   * <code>string consultation_id = 2;</code>
   * @return The bytes for consultationId.
   */
  com.google.protobuf.ByteString
      getConsultationIdBytes();

  /**
   * <code>int32 uplink_kbps = 3;</code>
   * @return The uplinkKbps.
   */
  int getUplinkKbps();

  /**
   * <code>int32 packet_loss = 4;</code>
   * @return The packetLoss.
   */
  int getPacketLoss();
}
