// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collab.proto

// Protobuf Java Version: 3.25.1
package com.mdt.collab.grpc;

/**
 * Protobuf type {@code mdt.collab.QualityReport}
 */
public final class QualityReport extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mdt.collab.QualityReport)
    QualityReportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QualityReport.newBuilder() to construct.
  private QualityReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QualityReport() {
    consultationId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QualityReport();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_QualityReport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_QualityReport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdt.collab.grpc.QualityReport.class, com.mdt.collab.grpc.QualityReport.Builder.class);
  }

  private int bitField0_;
  public static final int TRACE_FIELD_NUMBER = 1;
  private com.mdt.collab.grpc.Trace trace_;
  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   * @return Whether the trace field is set.
   */
  @java.lang.Override
  public boolean hasTrace() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   * @return The trace.
   */
  @java.lang.Override
  public com.mdt.collab.grpc.Trace getTrace() {
    return trace_ == null ? com.mdt.collab.grpc.Trace.getDefaultInstance() : trace_;
  }
  /**
   * <code>.mdt.collab.Trace trace = 1;</code>
   */
  @java.lang.Override
  public com.mdt.collab.grpc.TraceOrBuilder getTraceOrBuilder() {
    return trace_ == null ? com.mdt.collab.grpc.Trace.getDefaultInstance() : trace_;
  }

  public static final int CONSULTATION_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object consultationId_ = "";
  /**
   * <code>string consultation_id = 2;</code>
   * @return The consultationId.
   */
  @java.lang.Override
  public java.lang.String getConsultationId() {
    java.lang.Object ref = consultationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consultationId_ = s;
      return s;
    }
  }
  /**
   * <code>string consultation_id = 2;</code>
   * @return The bytes for consultationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConsultationIdBytes() {
    java.lang.Object ref = consultationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consultationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPLINK_KBPS_FIELD_NUMBER = 3;
  private int uplinkKbps_ = 0;
  /**
   * <code>int32 uplink_kbps = 3;</code>
   * @return The uplinkKbps.
   */
  @java.lang.Override
  public int getUplinkKbps() {
    return uplinkKbps_;
  }

  public static final int PACKET_LOSS_FIELD_NUMBER = 4;
  private int packetLoss_ = 0;
  /**
   * <code>int32 packet_loss = 4;</code>
   * @return The packetLoss.
   */
  @java.lang.Override
  public int getPacketLoss() {
    return packetLoss_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consultationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, consultationId_);
    }
    if (uplinkKbps_ != 0) {
      output.writeInt32(3, uplinkKbps_);
    }
    if (packetLoss_ != 0) {
      output.writeInt32(4, packetLoss_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTrace());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(consultationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, consultationId_);
    }
    if (uplinkKbps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, uplinkKbps_);
    }
    if (packetLoss_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, packetLoss_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdt.collab.grpc.QualityReport)) {
      return super.equals(obj);
    }
    com.mdt.collab.grpc.QualityReport other = (com.mdt.collab.grpc.QualityReport) obj;

    if (hasTrace() != other.hasTrace()) return false;
    if (hasTrace()) {
      if (!getTrace()
          .equals(other.getTrace())) return false;
    }
    if (!getConsultationId()
        .equals(other.getConsultationId())) return false;
    if (getUplinkKbps()
        != other.getUplinkKbps()) return false;
    if (getPacketLoss()
        != other.getPacketLoss()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTrace()) {
      hash = (37 * hash) + TRACE_FIELD_NUMBER;
      hash = (53 * hash) + getTrace().hashCode();
    }
    hash = (37 * hash) + CONSULTATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConsultationId().hashCode();
    hash = (37 * hash) + UPLINK_KBPS_FIELD_NUMBER;
    hash = (53 * hash) + getUplinkKbps();
    hash = (37 * hash) + PACKET_LOSS_FIELD_NUMBER;
    hash = (53 * hash) + getPacketLoss();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdt.collab.grpc.QualityReport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.mdt.collab.grpc.QualityReport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.mdt.collab.grpc.QualityReport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdt.collab.grpc.QualityReport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdt.collab.grpc.QualityReport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mdt.collab.QualityReport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mdt.collab.QualityReport)
      com.mdt.collab.grpc.QualityReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_QualityReport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_QualityReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdt.collab.grpc.QualityReport.class, com.mdt.collab.grpc.QualityReport.Builder.class);
    }

    // Construct using com.mdt.collab.grpc.QualityReport.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTraceFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      consultationId_ = "";
      uplinkKbps_ = 0;
      packetLoss_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdt.collab.grpc.Collab.internal_static_mdt_collab_QualityReport_descriptor;
    }

    @java.lang.Override
    public com.mdt.collab.grpc.QualityReport getDefaultInstanceForType() {
      return com.mdt.collab.grpc.QualityReport.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdt.collab.grpc.QualityReport build() {
      com.mdt.collab.grpc.QualityReport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdt.collab.grpc.QualityReport buildPartial() {
      com.mdt.collab.grpc.QualityReport result = new com.mdt.collab.grpc.QualityReport(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.mdt.collab.grpc.QualityReport result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.trace_ = traceBuilder_ == null
            ? trace_
            : traceBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.consultationId_ = consultationId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.uplinkKbps_ = uplinkKbps_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.packetLoss_ = packetLoss_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdt.collab.grpc.QualityReport) {
        return mergeFrom((com.mdt.collab.grpc.QualityReport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdt.collab.grpc.QualityReport other) {
      if (other == com.mdt.collab.grpc.QualityReport.getDefaultInstance()) return this;
      if (other.hasTrace()) {
        mergeTrace(other.getTrace());
      }
      if (!other.getConsultationId().isEmpty()) {
        consultationId_ = other.consultationId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getUplinkKbps() != 0) {
        setUplinkKbps(other.getUplinkKbps());
      }
      if (other.getPacketLoss() != 0) {
        setPacketLoss(other.getPacketLoss());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTraceFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              consultationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              uplinkKbps_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              packetLoss_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.mdt.collab.grpc.Trace trace_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.collab.grpc.Trace, com.mdt.collab.grpc.Trace.Builder, com.mdt.collab.grpc.TraceOrBuilder> traceBuilder_;
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     * @return Whether the trace field is set.
     */
    public boolean hasTrace() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     * @return The trace.
     */
    public com.mdt.collab.grpc.Trace getTrace() {
      if (traceBuilder_ == null) {
        return trace_ == null ? com.mdt.collab.grpc.Trace.getDefaultInstance() : trace_;
      } else {
        return traceBuilder_.getMessage();
      }
    }
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     */
    public Builder setTrace(com.mdt.collab.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trace_ = value;
      } else {
        traceBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     */
    public Builder setTrace(
        com.mdt.collab.grpc.Trace.Builder builderForValue) {
      if (traceBuilder_ == null) {
        trace_ = builderForValue.build();
      } else {
        traceBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     */
    public Builder mergeTrace(com.mdt.collab.grpc.Trace value) {
      if (traceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          trace_ != null &&
          trace_ != com.mdt.collab.grpc.Trace.getDefaultInstance()) {
          getTraceBuilder().mergeFrom(value);
        } else {
          trace_ = value;
        }
      } else {
        traceBuilder_.mergeFrom(value);
      }
      if (trace_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     */
    public Builder clearTrace() {
      bitField0_ = (bitField0_ & ~0x00000001);
      trace_ = null;
      if (traceBuilder_ != null) {
        traceBuilder_.dispose();
        traceBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     */
    public com.mdt.collab.grpc.Trace.Builder getTraceBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTraceFieldBuilder().getBuilder();
    }
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     */
    public com.mdt.collab.grpc.TraceOrBuilder getTraceOrBuilder() {
      if (traceBuilder_ != null) {
        return traceBuilder_.getMessageOrBuilder();
      } else {
        return trace_ == null ?
            com.mdt.collab.grpc.Trace.getDefaultInstance() : trace_;
      }
    }
    /**
     * <code>.mdt.collab.Trace trace = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mdt.collab.grpc.Trace, com.mdt.collab.grpc.Trace.Builder, com.mdt.collab.grpc.TraceOrBuilder> 
        getTraceFieldBuilder() {
      if (traceBuilder_ == null) {
        traceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mdt.collab.grpc.Trace, com.mdt.collab.grpc.Trace.Builder, com.mdt.collab.grpc.TraceOrBuilder>(
                getTrace(),
                getParentForChildren(),
                isClean());
        trace_ = null;
      }
      return traceBuilder_;
    }

    private java.lang.Object consultationId_ = "";
    /**
     * <code>string consultation_id = 2;</code>
     * @return The consultationId.
     */
    public java.lang.String getConsultationId() {
      java.lang.Object ref = consultationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consultationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string consultation_id = 2;</code>
     * @return The bytes for consultationId.
     */
    public com.google.protobuf.ByteString
        getConsultationIdBytes() {
      java.lang.Object ref = consultationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consultationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string consultation_id = 2;</code>
     * @param value The consultationId to set.
     * @return This builder for chaining.
     */
    public Builder setConsultationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      consultationId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string consultation_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConsultationId() {
      consultationId_ = getDefaultInstance().getConsultationId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string consultation_id = 2;</code>
     * @param value The bytes for consultationId to set.
     * @return This builder for chaining.
     */
    public Builder setConsultationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      consultationId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int uplinkKbps_ ;
    /**
     * <code>int32 uplink_kbps = 3;</code>
     * @return The uplinkKbps.
     */
    @java.lang.Override
    public int getUplinkKbps() {
      return uplinkKbps_;
    }
    /**
     * <code>int32 uplink_kbps = 3;</code>
     * @param value The uplinkKbps to set.
     * @return This builder for chaining.
     */
    public Builder setUplinkKbps(int value) {

      uplinkKbps_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 uplink_kbps = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUplinkKbps() {
      bitField0_ = (bitField0_ & ~0x00000004);
      uplinkKbps_ = 0;
      onChanged();
      return this;
    }

    private int packetLoss_ ;
    /**
     * <code>int32 packet_loss = 4;</code>
     * @return The packetLoss.
     */
    @java.lang.Override
    public int getPacketLoss() {
      return packetLoss_;
    }
    /**
     * <code>int32 packet_loss = 4;</code>
     * @param value The packetLoss to set.
     * @return This builder for chaining.
     */
    public Builder setPacketLoss(int value) {

      packetLoss_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 packet_loss = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPacketLoss() {
      bitField0_ = (bitField0_ & ~0x00000008);
      packetLoss_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mdt.collab.QualityReport)
  }

  // @@protoc_insertion_point(class_scope:mdt.collab.QualityReport)
  private static final com.mdt.collab.grpc.QualityReport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdt.collab.grpc.QualityReport();
  }

  public static com.mdt.collab.grpc.QualityReport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QualityReport>
      PARSER = new com.google.protobuf.AbstractParser<QualityReport>() {
    @java.lang.Override
    public QualityReport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QualityReport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QualityReport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdt.collab.grpc.QualityReport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

