// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: collab.proto

// Protobuf Java Version: 3.25.1
package com.mdt.collab.grpc;

public interface TraceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.collab.Trace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trace_id = 1;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string trace_id = 1;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>string tenant_id = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string operator_id = 3;</code>
   * @return The operatorId.
   */
  java.lang.String getOperatorId();
  /**
   * <code>string operator_id = 3;</code>
   * @return The bytes for operatorId.
   */
  com.google.protobuf.ByteString
      getOperatorIdBytes();
}
