// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

// Protobuf Java Version: 3.25.3
package com.mdt.auth.grpc;

public interface AuditRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.auth.AuditRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trace_id = 1;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string trace_id = 1;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>string tenant_id = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string operator_id = 3;</code>
   * @return The operatorId.
   */
  java.lang.String getOperatorId();
  /**
   * <code>string operator_id = 3;</code>
   * @return The bytes for operatorId.
   */
  com.google.protobuf.ByteString
      getOperatorIdBytes();

  /**
   * <code>string patient_visit_uid = 4;</code>
   * @return The patientVisitUid.
   */
  java.lang.String getPatientVisitUid();
  /**
   * <code>string patient_visit_uid = 4;</code>
   * @return The bytes for patientVisitUid.
   */
  com.google.protobuf.ByteString
      getPatientVisitUidBytes();

  /**
   * <code>string action = 5;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <code>string action = 5;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>int64 ts = 6;</code>
   * @return The ts.
   */
  long getTs();

  /**
   * <code>string detail = 7;</code>
   * @return The detail.
   */
  java.lang.String getDetail();
  /**
   * <code>string detail = 7;</code>
   * @return The bytes for detail.
   */
  com.google.protobuf.ByteString
      getDetailBytes();
}
