// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

// Protobuf Java Version: 3.25.3
package com.mdt.auth.grpc;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_auth_FieldPermissionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_auth_FieldPermissionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_auth_FieldPermissionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_auth_FieldPermissionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_auth_AuditRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_auth_AuditRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mdt_auth_Ack_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mdt_auth_Ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\010mdt.auth\"l\n\026FieldPermissio" +
      "nRequest\022\020\n\010trace_id\030\001 \001(\t\022\021\n\ttenant_id\030" +
      "\002 \001(\t\022\014\n\004role\030\003 \001(\t\022\020\n\010resource\030\004 \001(\t\022\r\n" +
      "\005field\030\005 \001(\t\"*\n\027FieldPermissionResponse\022" +
      "\017\n\007allowed\030\001 \001(\010\"\216\001\n\013AuditRecord\022\020\n\010trac" +
      "e_id\030\001 \001(\t\022\021\n\ttenant_id\030\002 \001(\t\022\023\n\013operato" +
      "r_id\030\003 \001(\t\022\031\n\021patient_visit_uid\030\004 \001(\t\022\016\n" +
      "\006action\030\005 \001(\t\022\n\n\002ts\030\006 \001(\003\022\016\n\006detail\030\007 \001(" +
      "\t\"\"\n\003Ack\022\n\n\002ok\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\236\001" +
      "\n\013AuthService\022[\n\024CheckFieldPermission\022 ." +
      "mdt.auth.FieldPermissionRequest\032!.mdt.au" +
      "th.FieldPermissionResponse\0222\n\nWriteAudit" +
      "\022\025.mdt.auth.AuditRecord\032\r.mdt.auth.AckB\025" +
      "\n\021com.mdt.auth.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mdt_auth_FieldPermissionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mdt_auth_FieldPermissionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_auth_FieldPermissionRequest_descriptor,
        new java.lang.String[] { "TraceId", "TenantId", "Role", "Resource", "Field", });
    internal_static_mdt_auth_FieldPermissionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mdt_auth_FieldPermissionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_auth_FieldPermissionResponse_descriptor,
        new java.lang.String[] { "Allowed", });
    internal_static_mdt_auth_AuditRecord_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mdt_auth_AuditRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_auth_AuditRecord_descriptor,
        new java.lang.String[] { "TraceId", "TenantId", "OperatorId", "PatientVisitUid", "Action", "Ts", "Detail", });
    internal_static_mdt_auth_Ack_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mdt_auth_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mdt_auth_Ack_descriptor,
        new java.lang.String[] { "Ok", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
