// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

// Protobuf Java Version: 3.25.3
package com.mdt.auth.grpc;

public interface FieldPermissionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.auth.FieldPermissionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool allowed = 1;</code>
   * @return The allowed.
   */
  boolean getAllowed();
}
