// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

// Protobuf Java Version: 3.25.3
package com.mdt.auth.grpc;

public interface FieldPermissionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mdt.auth.FieldPermissionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string trace_id = 1;</code>
   * @return The traceId.
   */
  java.lang.String getTraceId();
  /**
   * <code>string trace_id = 1;</code>
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>string tenant_id = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <code>string tenant_id = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <code>string role = 3;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 3;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <pre>
   * 如 "study.endoscopy"
   * </pre>
   *
   * <code>string resource = 4;</code>
   * @return The resource.
   */
  java.lang.String getResource();
  /**
   * <pre>
   * 如 "study.endoscopy"
   * </pre>
   *
   * <code>string resource = 4;</code>
   * @return The bytes for resource.
   */
  com.google.protobuf.ByteString
      getResourceBytes();

  /**
   * <pre>
   * 如 "pathology_conclusion"
   * </pre>
   *
   * <code>string field = 5;</code>
   * @return The field.
   */
  java.lang.String getField();
  /**
   * <pre>
   * 如 "pathology_conclusion"
   * </pre>
   *
   * <code>string field = 5;</code>
   * @return The bytes for field.
   */
  com.google.protobuf.ByteString
      getFieldBytes();
}
